name: SonarQube Analysis

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

jobs:
  sonarQube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Run Tests and SonarQube Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        working-directory: ./jSymbolic2
        run: |
            ./gradlew build sonar \
            -Dsonar.projectKey=jSymbolic2 \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_LOGIN }} \
            -Dsonar.password=${{ secrets.SONAR_PASSWORD }} \
            -Dsonar.branch.name=${GITHUB_REF##*/} \
            -Dsonar.binaries=build/classes \
            -Dsonar.dynamicAnalysis=reuseReports \
            -Dsonar.junit.reportsPath=build/test-results \
            -Dsonar.java.coveragePlugin=jacoco \
            -Dsonar.jacoco.reportPath=build/jacoco/test.exec \
            -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml --scan

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
      # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
        with:
          build-root-directory: ./jSymbolic2
